name: omni_retail
version: "1.0.0"
config-version: 2

profile: omni_retail

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  omni_retail:
    staging:
      +materialized: view
      +schema: "{{ env_var('DBT_SILVER_SCHEMA', 'silver') }}"
    intermediate:
      +materialized: view
      +schema: "{{ env_var('DBT_SILVER_SCHEMA', 'silver') }}"
    core:
      +materialized: table
      +schema: "{{ env_var('DBT_GOLD_SCHEMA', 'gold') }}"
    marts:
      +materialized: table
      +schema: "{{ env_var('DBT_ANALYTICS_SCHEMA', 'analytics') }}"
