-- OmniRetail OLTP schema (Phase 2).
-- Applied automatically on first start of the postgres container
-- (mounted into /docker-entrypoint-initdb.d). Idempotent so the
-- generator can safely re-apply it against an existing database.

BEGIN;

CREATE TABLE IF NOT EXISTS categories (
    category_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               text NOT NULL UNIQUE,
    parent_category_id bigint REFERENCES categories (category_id),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
    product_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         text NOT NULL UNIQUE,
    name        text NOT NULL,
    category_id bigint NOT NULL REFERENCES categories (category_id),
    brand       text NOT NULL,
    unit_price  numeric(12,2) NOT NULL CHECK (unit_price > 0),
    unit_cost   numeric(12,2) NOT NULL CHECK (unit_cost >= 0 AND unit_cost <= unit_price),
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_category_id ON products (category_id);

CREATE TABLE IF NOT EXISTS customers (
    customer_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         text NOT NULL UNIQUE,
    first_name    text NOT NULL,
    last_name     text NOT NULL,
    region        text NOT NULL,
    city          text NOT NULL,
    status        text NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'inactive', 'churned')),
    segment       text NOT NULL DEFAULT 'standard'
                  CHECK (segment IN ('standard', 'premium', 'vip')),
    registered_at timestamptz NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customers_updated_at ON customers (updated_at);

CREATE TABLE IF NOT EXISTS orders (
    order_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   bigint NOT NULL REFERENCES customers (customer_id),
    status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded')),
    currency      text NOT NULL DEFAULT 'USD'
                  CHECK (currency IN ('USD', 'EUR', 'GBP')),
    shipping_cost numeric(12,2) NOT NULL DEFAULT 0 CHECK (shipping_cost >= 0),
    order_total   numeric(12,2) NOT NULL CHECK (order_total >= 0),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_orders_updated_at ON orders (updated_at);

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint NOT NULL REFERENCES orders (order_id) ON DELETE CASCADE,
    product_id    bigint NOT NULL REFERENCES products (product_id),
    quantity      integer NOT NULL CHECK (quantity > 0),
    unit_price    numeric(12,2) NOT NULL CHECK (unit_price > 0),
    line_total    numeric(12,2) NOT NULL CHECK (line_total >= 0),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items (product_id);

CREATE TABLE IF NOT EXISTS payments (
    payment_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       bigint NOT NULL UNIQUE REFERENCES orders (order_id) ON DELETE CASCADE,
    method         text NOT NULL
                   CHECK (method IN ('card', 'paypal', 'bank_transfer', 'cash_on_delivery')),
    status         text NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'authorized', 'captured', 'failed', 'refunded', 'cancelled')),
    amount         numeric(12,2) NOT NULL CHECK (amount > 0),
    transaction_id text NOT NULL UNIQUE,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shipments (
    shipment_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint NOT NULL UNIQUE REFERENCES orders (order_id) ON DELETE CASCADE,
    carrier         text NOT NULL
                    CHECK (carrier IN ('express_air', 'express_ground', 'postal', 'courier')),
    tracking_number text NOT NULL UNIQUE,
    status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'in_transit', 'delivered', 'cancelled')),
    shipped_at      timestamptz,
    delivered_at    timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CHECK (delivered_at IS NULL OR shipped_at IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_shipments_status ON shipments (status);

COMMIT;
